name: Update this repo's README with latest blog posts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.mk1.io/api/feed"
          max_post_count: "3"
